swagger: "2.0"
info:
  description: "Foobar"
  version: "1.0.0"
  title: "Ocius Api"
host: "api.ocius.com.au"
paths:
  /drone/{name}:
    get:
      tags:
      - "drone"
      summary: "Get drone lat and long by name"
      description: "Returns the current lat and long of a single drone"
      operationId: "GetDroneByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of drone"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Drone"
        404:
          description: "Drone not found"
    

definitions:
  Drone:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      timestamp:
        type: "integer"
      data:
        type: "string"
  